language: php

sudo: false

php:
 - 5.6

env:
  matrix:
    - PHPUNIT_TEST=1
    - PHPCS_TEST=1

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_TEST=1
    - php: 7.0
      env: PHPUNIT_TEST=1
    - php: 7.1
      env: PHPUNIT_TEST=1

before_script:
  - composer validate
  - composer install --dev --prefer-dist
  - composer require silverstripe/config:1.0.x-dev silverstripe/framework:4.0.x-dev --prefer-dist
  - "if [ \"$PHPCS_TEST\" = \"1\" ]; then pyrus install pear/PHP_CodeSniffer; fi"
  - phpenv rehash


script:
  - "if [ \"$PHPUNIT_TEST\" = \"1\" ]; then vendor/bin/phpunit tests; fi"
  - "if [ \"$PHPCS_TEST\" = \"1\" ]; then phpcs --standard=PSR2 -n src/ tests/; fi"
