parameters:
  silverstripe_extension.context.initializer.class: SilverStripe\BehatExtension\Context\Initializer\SilverStripeAwareInitializer
  silverstripe_extension.context.class_guesser.class: SilverStripe\BehatExtension\Context\ClassGuesser\ModuleContextClassGuesser
  console.processor.locator.class: SilverStripe\BehatExtension\Console\Processor\LocatorProcessor
  console.processor.init.class: SilverStripe\BehatExtension\Console\Processor\InitProcessor
  silverstripe_extension.context.namespace_suffix: Test\Behaviour
  silverstripe_extension.framework_path: framework
  silverstripe_extension.ajax_steps: ~
  silverstripe_extension.ajax_timeout: ~
  silverstripe_extension.admin_url: ~
  silverstripe_extension.login_url: ~
  silverstripe_extension.screenshot_path: ~
  silverstripe_extension.module:
  silverstripe_extension.region_map: ~
  silverstripe_extension.context.path_suffix: tests/behat/features/
services:
  silverstripe_extension.context.initializer:
    class: %silverstripe_extension.context.initializer.class%
    arguments:
      - %silverstripe_extension.framework_path%
    calls:
      - [setAjaxSteps, [%silverstripe_extension.ajax_steps%]]
      - [setAjaxTimeout, [%silverstripe_extension.ajax_timeout%]]
      - [setAdminUrl, [%silverstripe_extension.admin_url%]]
      - [setLoginUrl, [%silverstripe_extension.login_url%]]
      - [setScreenshotPath, [%silverstripe_extension.screenshot_path%]]
      - [setRegionMap, [%silverstripe_extension.region_map%]]
    tags:
      - { name: context.initializer }
  silverstripe_extension.context.class_guesser:
    class: %silverstripe_extension.context.class_guesser.class%
    arguments:
      - %silverstripe_extension.context.namespace_suffix%
      - FeatureContext
    tags:
      - { name: silverstripe_extension.context.class_guesser.class, priority: 10 }